language: ruby
sudo: required
rvm:
  - 2.5.0
  - 2.4.0
  - 2.3.3
  - jruby-9000
before_install:
  - gem install bundler
  - gem update --system
install: bin/setup
script:
  - cd ext/argon2_wrap/ && make test && cd ../..
  - bundle exec rake test
