language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - jruby-9000
before_install:
  - gem install bundler
  - gem update --system
install: bin/setup
script:
  - cd ext/argon2_wrap/ && make test && cd ../..
  - bundle exec rake test
  - CODECLIMATE_REPO_TOKEN=28e3d5d04f4ec87d0899784e6aecc13d7787343b2634b3c94fc1216993d443c2 bundle exec codeclimate-test-reporter
